### ISSUE TITLE
RISC-V Toolchain

### ISSUE THREAD

**Issue by duncangraham-Imperas** [riscv-non-isa/riscv-arch-test#249] opened 2022-04-08 09:16 UTC
I attempted to run the lastest master branch but with the changes for the ratified crypto (K) tests I now get assembler errors for the xperm8 instruction.
Could you recommend a source of a binary GNU GCC cross-compiler toolchain that satisifes these tests?

**Comment by allenjbaum** [comment] 2022-04-11 06:40
Could this because xperm is in the Zbkx extension, which makes it look like
it's a bitmanip op - except it was never a ratified?
You may have to explicitly list Zbkx in the march string (this is a guess)

**Comment by allenjbaum** [comment] 2022-04-22 23:41
Have you tried this fix?

**Comment by allenjbaum** [comment] 2022-04-22 23:58
also: have you tried running this under riscof?

**Comment by Imperas** [comment] 2022-04-25 09:59
@allenjbaum does riscof have its own tool chains? surely not. 
why would running under riscof change the toolchain installation.

can you pls get somebody to answer Duncan's question 'Could you recommend a source of a binary GNU GCC cross-compiler toolchain that satisifes these tests?'
thnx
Simon

**Comment by allenjbaum** [comment] 2022-04-27 06:40
As far as I know we have people using it all the time with these tests. so I don't know what the problem is.
i'll see what I can find out.

**Comment by Imperas** [comment] 2022-04-27 13:11
Thanks @pawks  for this info - can you respond with the location to download a toolchain that accepts this option. thanks. Simon

**Comment by allenjbaum** [comment] 2022-04-27 15:07
Can I assume that you've applied the fix to the makefile, and it doesn't work on the version of the toolchain that previously failed?

**Comment by duncangraham-Imperas** [comment] 2022-04-27 15:18
Yes, replaced _rv64ib_ with _rv64iZbkx_ in _riscv-test-suite/rv64i_m/K/Makefile_. With the toolchain I have previously used successfully for these tests (and when also trying with others) I get the error :
  _riscv64-unknown-elf-gcc: error: '-march=rv64iZbkx': unsupported ISA subset 'Z'_
Thanks for your help

**Comment by neelgala** [comment] 2022-05-26 15:24
tests currently checked in will require `RVTEST_ISA` macro updates to get the dut-plugins notified of the extensions required to compile these tests.

**Comment by allenjbaum** [comment] 2023-02-09 03:21
Duncan, I haven't seen this closed or a note that says it is still broken. I'm going to close this and you can reopen it if it isn't fixed

**Closed by allenjbaum** 2023-02-09 03:21 UTC
